export const fontFamily = {
  sans: [
    "DM Sans",
    "ui-sans-serif",
    "system-ui",
    "-apple-system",
    "BlinkMacSystemFont",
    "Segoe UI",
    "Roboto",
    "Helvetica Neue",
    "Arial",
    "Noto Sans",
    "sans-serif",
    "Apple Color Emoji",
    "Segoe UI Emoji",
    "Segoe UI Symbol",
    "Noto Color Emoji",
  ],
  mono: [
    "DM Mono",
    "Menlo",
    "Consolas",
    "Monaco",
    "Liberation Mono",
    "Lucida Console",
    "monospace",
  ],
};
