import {
  blink,
  bounce,
  fadeIn,
  fadeOut,
  float,
  ping,
  pulse,
  scaleDown,
  scaleUp,
  shakeX,
  shakeY,
  slideInDown,
  slideInLeft,
  slideInRight,
  slideInUp,
  slideOutDown,
  slideOutLeft,
  slideOutRight,
  slideOutUp,
  spin,
} from './util/animations';
import { ease3, easeInOut3, easeOut3, easeOut5, easeSquish2 } from './util/easing';
import { mediaQueries } from './util/media';

export type ThemeType = typeof defaultTheme;

const defaultTheme = {
  animations: {
    '--animation-fade-in': `${fadeIn} .5s ${ease3}`,
    '--animation-fade-out': `${fadeOut} .5s ${ease3}`,
    '--animation-scale-up': `${scaleUp} .5s ${ease3}`,
    '--animation-scale-down': `${scaleDown} .5s ${ease3}`,
    '--animation-slide-out-up': `${slideOutUp} .5s ${ease3}`,
    '--animation-slide-out-down': `${slideOutDown} .5s ${ease3}`,
    '--animation-slide-out-right': `${slideOutRight} .5s ${ease3}`,
    '--animation-slide-out-left': `${slideOutLeft} .5s ${ease3}`,
    '--animation-slide-in-up': `${slideInUp} .5s ${ease3}`,
    '--animation-slide-in-down': `${slideInDown} .5s ${ease3}`,
    '--animation-slide-in-right': `${slideInRight} .5s ${ease3}`,
    '--animation-slide-in-left': `${slideInLeft} .5s ${ease3}`,
    '--animation-shake-x': `${shakeX} .75s ${easeOut5}`,
    '--animation-shake-y': `${shakeY} .75s ${easeOut5}`,
    '--animation-spin': `${spin} 2s linear infinite`,
    '--animation-ping': `${ping} 5s ${easeOut3} infinite`,
    '--animation-blink': `${blink} 1s ${easeOut3} infinite`,
    '--animation-float': `${float} 3s ${easeInOut3} infinite`,
    '--animation-bounce': `${bounce} 2s ${easeSquish2} infinite`,
    '--animation-pulse': `${pulse} 2s ${easeOut3} infinite`,
  },
  borders: {},
  brand: {},
  colors: {},
  easing: {},
  fonts: {},
  gradients: {},
  highlights: {},
  media: {
    '--max-screen320': mediaQueries.maxScreen320,
    '--mobile-m': mediaQueries.mobileM,
    '--mobile-l': mediaQueries.mobileL,
    '--mobile-xl': mediaQueries.mobileXL,
    '--tablet': mediaQueries.tablet,
    '--laptop': mediaQueries.laptop,
    '--laptop-l': mediaQueries.laptopL,
    '--laptop-xl': mediaQueries.laptopXL,
    '--desktop': mediaQueries.desktop,
    '--desktop-l': mediaQueries.desktopL,
    '--motion-ok': mediaQueries.motionOK,
    '--motion-not-ok': mediaQueries.motionNotOK,
    '--opacity-ok': mediaQueries.opacityOK,
    '--opacity-not-ok': mediaQueries.opacityNotOK,
    '--use-data-ok': mediaQueries.useDataOK,
    '--use-data-not-ok': mediaQueries.useDataNotOK,
    '--os-dark': mediaQueries.OSdark,
    '--os-light': mediaQueries.OSlight,
    '--high-contrast': mediaQueries.highContrast,
    '--low-contrast': mediaQueries.lowContrast,
    '--portrait': mediaQueries.portrait,
    '--landscape': mediaQueries.landscape,
    '--hd-color': mediaQueries.HDcolor,
    '--touch': mediaQueries.touch,
    '--stylus': mediaQueries.stylus,
    '--pointer': mediaQueries.pointer,
    '--mouse': mediaQueries.mouse,
  },
  shadows: {},
  sizes: {},
  zIndex: {},
};

export const lightTheme = {};

export const darkTheme = {};

export default defaultTheme;
