name: GitHub Actions OIDC Test

on:
  push:
    branches:
      - main

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      # Install Dependencies
      - run: bun install

      # Publish
      - run: bun release
